hr:
    salary:
        def:
            percent: 5
        smart:
            maxPaymentRaisePercentage: 10
            maxYearsOfPaymentRaise: 10.0
            medYearsOfPaymentRaise: 5.0
            mediumPaymentRaisePercentage: 5
            minPaymentRaisePercentage: 2
            minYearsOfPaymentRaise: 2.5
spring:
    mvc:
        format:
            date-time: yyyy-MM-dd HH:mm:ss
    profiles:
        active: smart
    thymleaf:
        cache: false

