hr:
  salary:
    def:
      percent: 5
    smart:
      limit:
        maxYearsOfPaymentRaise: 10
        medYearsOfPaymentRaise: 5
        minMonthsOfPaymentRaise: 30
      maxPaymentRaisePercentage: 10
      mediumPaymentRaisePercentage: 5
      minPaymentRaisePercentage: 2
spring:
  profiles:
    active: smart
